[env:black_f407zg]
upload_protocol = stlink
platform = ststm32
board = black_f407zg
framework = stm32cube
monitor_speed = 115200
extra_scripts = post:fpu_link.py
build_flags =
    -I$PROJECT_DIR/include
    -I$PROJECT_DIR/lib/FreeRTOS-Kernel/include
    -I$PROJECT_DIR/lib/FreeRTOS-Kernel/portable/GCC/ARM_CM4F
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard